Traceback (most recent call last):
  File "/home/johnma/afdps-pde/train.py", line 68, in <module>
    train_loader, _ = get_loaders(config)
  File "/home/johnma/afdps-pde/utils.py", line 30, in get_loaders
    print(f"Train set shape: {dataset['train'].shape}")
KeyError: 'train'
